try{
    console.log(a);
} catch(err){
    console.log(err);
}